# -*- coding: utf-8 -*-
"""Reto_8_7

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tshokGL2cSE-uYYZt6gtUUYhb_QpPabP
"""

for num in range(1,11):
  for f in range(1,11):
    multiplicacion = num * f
    print(str(num)+ " x " +str(f)+ " = " +str(multiplicacion))
  print("Fin de la tabla")