# -*- coding: utf-8 -*-
"""Reto_8_4

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DF91eAr1JgL9FcFPse1fL91fgrTgUtSR
"""

numero = int(input("Ingrese un numero natural: "))
inicio : int = 1
fact : int = 1
for inicio in range(1, numero + 1,1):
  for i in range(1, inicio +1):
    fact = fact*i
  print("Fatorial de " +str(inicio)+ " es " +str(fact))
  fact = 1