# -*- coding: utf-8 -*-
"""Reto_8_10

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10i-Irk5JgenLjWE256sM0qcG9F7Bo60K
"""

from math import factorial
from numpy import arctan

def aprox_arctg(numero: float, n: int)-> float:
  suma: float = 0
  for i in range(0, n+1):
    n_ter = (((-1)**i)*((numero**(2*i+1))/(2*i+1)))
    suma += n_ter
  return suma

if __name__ == "__main__":
  numero = float(input("Ingresa un número real "))
  n: int = 1
  aprx: float = aprox_arctg(numero, n)
  v_real : float = arctan(numero)

while((abs(v_real - aprx)/v_real * 100)>0.1):
  aprx: float = aprox_arctg(numero, n)
  n += 1
print("Para que el margen de error sea menor a 0.1  el valor debe ser:" +str(n))
print("La aproximación es " +str(aprx))
print("El valor real es " +str(v_real))