# -*- coding: utf-8 -*-
"""Reto_8_1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BSdx5UHhYT9tnpwpiHMxUiDF3zma3mE5
"""

for i in range(1, 101, 1):
  print(str(i)+ " y su cuadrado es " +str(i**2))