# -*- coding: utf-8 -*-
"""reto_8_9_1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17rVqF42tBp8wB5bN1qozfFzSmrd0uBCB
"""

from math import sin, factorial

def aprox_sin(numero: float, n: int)-> float:
  suma: float = 0
  for i in range(0, n+1):
    n_ter = (((-1)**i)*((numero**(2*i+1))/(factorial(2*i+1))))
    suma += n_ter
  return suma

if __name__ == "__main__":
  numero = float(input("Ingresa un número real "))
  n: int = 10
  aprx: float = aprox_sin(numero, n)
  v_real : float = sin(numero)
  vabs : float = ((abs(v_real - aprx))/abs(v_real) * 100)
  print("Aproximación :" +str(aprx))
  print("El valor real es " +str(v_real))
  print("Margen de error " +str(vabs)+ "%")