# -*- coding: utf-8 -*-
"""Reto_8_6

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vzxrZ1cun59spA6aQlTM1Brs7wh1_pnI
"""

numero_b = float(input("Ingresa un número real: "))
numero_a = int(input("Ingresa un número natural: "))
b = numero_b
for i in range(1,numero_a):
  numero_b = numero_b * b
print("El numero " +str(b)+" elevado a la potencia " +str(numero_a)+ " es : " +str(numero_b))