# -*- coding: utf-8 -*-
"""Reto_8_5

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1USs18Vw1JOu6K2PPrIcKVhr6uJd0WFi6
"""

num_c : int = 2
potencia = int(input("Ingresa el número que desees: "))
numero : int = 2
for i in range(1, potencia, 1):
  num_c = num_c *numero
print("2 elevado a la potencia " +str(potencia)+ " es igual a " +str(num_c))