# -*- coding: utf-8 -*-
"""Reto_8_2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tzxuBloAIIWYrqDiiNY6M9bmadszAw7h
"""

for i in range(2, 1000, 2):
  print(i, "Es par")
print("Hasta aqui van los pares")
for i in range(1, 1000, 1):
  print(i, "Es impar")
print("Hasta aqui van los impares")